name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
jobs:
  build:
    name: Release - ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/pid2pnid-pretendo
            target/release/pid2pnid-pretendo.exe
